#!/usr/bin/env bash
#
# Test script for Step 2: Voice Cloning and TTS
#
# This script tests the n8n workflow that clones a voice from reference audio
# and generates TTS of a script using vibevoice.

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
N8N_WEBHOOK_URL="${N8N_WEBHOOK_URL:-https://n8n.lan/webhook/voice-clone-tts}"
SCRIPT_TEXT="${SCRIPT_TEXT:-This is a test of voice cloning technology. The voice you hear is generated by AI.}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/test-tts}"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

echo -e "${YELLOW}=== Step 2: Voice Cloning and TTS Test ===${NC}"
echo ""
echo "Configuration:"
echo "  N8N Webhook: $N8N_WEBHOOK_URL"
echo "  Script: \"$SCRIPT_TEXT\""
echo "  Output Dir: $OUTPUT_DIR"
echo ""

# Check if we have a task_id from Step 1
if [ -n "${STEP1_TASK_ID:-}" ]; then
  echo -e "${GREEN}Using reference audio from Step 1 (task_id: $STEP1_TASK_ID)${NC}"
  REQUEST_PAYLOAD=$(cat <<EOF
{
  "script": "$SCRIPT_TEXT",
  "reference_task_id": "$STEP1_TASK_ID"
}
EOF
)
else
  # Check for local audio file
  REF_AUDIO="${REF_AUDIO:-/tmp/test-audio/extracted_audio.mp3}"

  if [ ! -f "$REF_AUDIO" ]; then
    echo -e "${RED}❌ No reference audio found!${NC}"
    echo ""
    echo "You need reference audio for voice cloning. Options:"
    echo ""
    echo "1. Run Step 1 first to extract audio from YouTube:"
    echo "   ./test-step1-audio-extraction.sh"
    echo "   Then run this script with: STEP1_TASK_ID=<task_id> $0"
    echo ""
    echo "2. Or provide your own audio file:"
    echo "   REF_AUDIO=/path/to/audio.mp3 $0"
    echo ""
    exit 1
  fi

  echo -e "${YELLOW}Using reference audio file: $REF_AUDIO${NC}"

  # Make request with file upload
  echo -e "${YELLOW}Sending request with audio file...${NC}"
  RESPONSE_FILE="$OUTPUT_DIR/response.json"
  TTS_AUDIO_FILE="$OUTPUT_DIR/cloned_voice.mp3"

  HTTP_CODE=$(curl -k -s -w "%{http_code}" \
    -X POST \
    -F "script=$SCRIPT_TEXT" \
    -F "reference_audio=@$REF_AUDIO" \
    "$N8N_WEBHOOK_URL" \
    -o "$RESPONSE_FILE")

  echo "HTTP Status Code: $HTTP_CODE"
  echo ""

  if [ "$HTTP_CODE" != "200" ]; then
    echo -e "${RED}❌ Request failed with status code: $HTTP_CODE${NC}"
    echo -e "${RED}Response:${NC}"
    cat "$RESPONSE_FILE"
    exit 1
  fi

  echo -e "${GREEN}✅ Request successful!${NC}"
  echo ""

  echo -e "${YELLOW}Response:${NC}"
  cat "$RESPONSE_FILE" | jq .
  echo ""

  # Check success
  SUCCESS=$(cat "$RESPONSE_FILE" | jq -r '.success // false')
  if [ "$SUCCESS" != "true" ]; then
    echo -e "${RED}❌ Workflow reported failure${NC}"
    exit 1
  fi

  FILE_NAME=$(cat "$RESPONSE_FILE" | jq -r '.file_name // "unknown"')

  echo -e "${GREEN}✅ Voice cloned and TTS generated successfully!${NC}"
  echo ""
  echo "Details:"
  echo "  File Name: $FILE_NAME"
  echo "  Script: \"$SCRIPT_TEXT\""
  echo ""

  echo -e "${GREEN}=== Step 2 Test PASSED ===${NC}"
  echo ""
  echo "Next steps:"
  echo "  1. The TTS audio should be in the response (check n8n execution)"
  echo "  2. Verify the voice sounds like the reference"
  echo "  3. If everything looks good, proceed to Step 3 (Image Generation)"

  exit 0
fi

# Create request payload with task_id
echo -e "${YELLOW}Request Payload:${NC}"
echo "$REQUEST_PAYLOAD" | jq .
echo ""

# Make request
echo -e "${YELLOW}Sending request to n8n workflow...${NC}"
RESPONSE_FILE="$OUTPUT_DIR/response.json"

HTTP_CODE=$(curl -k -s -w "%{http_code}" \
  -X POST \
  -H "Content-Type: application/json" \
  -d "$REQUEST_PAYLOAD" \
  "$N8N_WEBHOOK_URL" \
  -o "$RESPONSE_FILE")

echo "HTTP Status Code: $HTTP_CODE"
echo ""

if [ "$HTTP_CODE" != "200" ]; then
  echo -e "${RED}❌ Request failed with status code: $HTTP_CODE${NC}"
  echo -e "${RED}Response:${NC}"
  cat "$RESPONSE_FILE"
  exit 1
fi

echo -e "${GREEN}✅ Request successful!${NC}"
echo ""

# Parse response
echo -e "${YELLOW}Response:${NC}"
cat "$RESPONSE_FILE" | jq .
echo ""

# Check success
SUCCESS=$(cat "$RESPONSE_FILE" | jq -r '.success // false')
if [ "$SUCCESS" != "true" ]; then
  echo -e "${RED}❌ Workflow reported failure${NC}"
  exit 1
fi

FILE_NAME=$(cat "$RESPONSE_FILE" | jq -r '.file_name // "unknown"')

echo -e "${GREEN}✅ Voice cloned and TTS generated successfully!${NC}"
echo ""
echo "Details:"
echo "  File Name: $FILE_NAME"
echo "  Script: \"$SCRIPT_TEXT\""
echo ""

echo -e "${GREEN}=== Step 2 Test PASSED ===${NC}"
echo ""
echo "Next steps:"
echo "  1. The TTS audio should be in the response (check n8n execution)"
echo "  2. Verify the voice sounds like the reference"
echo "  3. If everything looks good, proceed to Step 3 (Image Generation)"
